window.CAN_BE_HAPPY_SUPABASE_URL = "https://jqdypqdqzsmrsbpgftqf.supabase.co";
window.CAN_BE_HAPPY_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZHlwcWRxenNtcnNicGdmdHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNzkyMTksImV4cCI6MjA5Mzc1NTIxOX0.abgPeCFtRxXgMWEzIIRy5EUAfsEsPqB8oXs_4B1DeFs";
